

// Generated by slyft.io
// This code part has been generated on an "as is" basis, without warranties or conditions of any kind.

// slyftlet=c99-generic-msgpack

#ifndef tut4_OLED_H
#define tut4_OLED_H

#include "mpack/mpack.h"

struct TUT4__oled {
  bool	OLED_stat;
  char	oled_display[4];

  /**
  * Wipes contents to \0
  * @param self      pointer to target struct TUT4__oled
  */
  void (*TUT4__oled_clean)(struct TUT4__oled *self);

  /**
  * Given an input buffer and its size, this functions parses the elements
  * of struct TUT4__oled
  * @param self          pointer to target struct TUT4__oled
  * @param input_buf     input buffer
  * @param sz_input_buf  size of input buffer
  * @return 0=success, 1=error
  */
  int (*TUT4__oled_parse)(struct TUT4__oled *self, const uint8_t *input_buf, size_t sz_input_buf);

  /**
  * Given a msgpack reader, this functions parses the elements
  * of struct TUT4__oled
  * @param self          pointer to target struct TUT4__oled
  * @param reader        pointer to mpack reader struct
  */
  void (*TUT4__oled_parse_mpack)(struct TUT4__oled *self, mpack_reader_t *reader);

  /**
  * Given a struct TUT4__oled, this function serializes it into given output buffer.
  * @param self              pointer to source struct TUT4__oled
  * @param output_buf        output buffer
  * @param sz_output_buf     size of output buffer
  * @return Length of output buf (0=error)
  */
  size_t (*TUT4__oled_serialize)(const struct TUT4__oled *self, uint8_t *output_buf, size_t sz_output_buf);

  /**
  * Given a struct TUT4__oled, this function serializes it into given mpack writer.
  * @param self              pointer to source struct TUT4__oled
  * @param writer 	         pointer to mpack writer struct
  */
  void (*TUT4__oled_serialize_mpack)(const struct TUT4__oled *self, mpack_writer_t *writer);

};

/**
 * Initializes struct struct TUT4__oled. empties fields, sets function pointers
 * @param self  struct TUT4__oled
 */
void TUT4__oled_init(struct TUT4__oled *self);


/* ORIGINAL SCHEMA
{"$schema"=>"http://json-schema.org/draft-04/schema#", "id"=>"oled", "title"=>"OLED", "description"=>"POST close/clean command to LED", "type"=>"object", "properties"=>{"OLED_stat"=>{"type"=>"boolean"}, "oled_display"=>{"type"=>"string", "maxLength"=>3}}, "required"=>["OLED_stat"]}
 */
#endif		//tut4_OLED_H

